pipeline {
    agent any

    stages{
        stage('Copying repository') {
            steps {
                git branch: 'main', credentialsId: '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', url: 'https://github.com/carlosngv/SA-G4-Practicas'
            }
        }
        stage('Terraform Init'){
            steps{
                sh 'cd Practica_5 && terraform init'
            }
        }
        stage('Terraform apply'){
            steps{
                sh 'cd Practica_5 && terraform apply -auto-approve'
            }
        }
    }

}
