pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/carlosngv/SA-G4-Practicas']]])

          }
        }

        stage ("terraform init") {
            steps {
                sh 'cd Practica_5 && terraform init'
            }
        }

        stage ("terraform Action") {
            steps {
                echo "Terraform action is --> ${action}"
                sh 'cd Practica_5 && terraform ${action} --auto-approve'
           }
        }
    }
}
